### ISSUE TITLE
Need HELP GUAIZ IM STUCK

### ISSUE THREAD

**Issue by carlosd2552** [carlosd2552/Group8-BSIT-WMA4B#3]
AS THE TITLE SAYSS
![begeta](https://user-images.githubusercontent.com/111640891/194710566-2b7f587a-21d5-4756-8693-18c9110b9c73.png)

**Comment by Anna-Mikaela** [comment]
hmnmnmn was dizzzzzzz

**Comment by patpinon** [comment]
hehe

**Comment by Anna-Mikaela** [comment]
aaaaaaaaaaaaaa

**Comment by Anna-Mikaela** [comment]
uhmnn auq n4h

**Comment by uglypotatoo** [comment]
magalit ka vegeta

**Comment by uglypotatoo** [comment]
1.

**Comment by uglypotatoo** [comment]
ay sorry
